
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int LT = 22;
  public static final int NE = 21;
  public static final int ELSE = 18;
  public static final int PLUS = 3;
  public static final int RBRACE = 10;
  public static final int RPAREN = 8;
  public static final int INT = 12;
  public static final int WHILE = 19;
  public static final int SEMI = 2;
  public static final int RETURN = 16;
  public static final int TRUE = 26;
  public static final int IF = 17;
  public static final int GT = 23;
  public static final int LPAREN = 7;
  public static final int LBRACE = 9;
  public static final int ID = 29;
  public static final int LE = 24;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MAIN = 15;
  public static final int FALSE = 27;
  public static final int GE = 25;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 20;
  public static final int ASSIGN = 11;
  public static final int BOOL = 13;
  public static final int VOID = 14;
  public static final int AND = 30;  // NUEVO - Operador lógico &&
  public static final int OR = 31;   // NUEVO - Operador lógico ||
  
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "ASSIGN",
  "INT",
  "BOOL",
  "VOID",
  "MAIN",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "EQ",
  "NE",
  "LT",
  "GT",
  "LE",
  "GE",
  "TRUE",
  "FALSE",
  "NUMBER",
  "ID",
  "AND",
  "OR"
  };
}