
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int AND = 28;
  public static final int LT = 24;
  public static final int NE = 23;
  public static final int ELSE = 20;
  public static final int PLUS = 3;
  public static final int OR = 29;
  public static final int RBRACE = 10;
  public static final int RPAREN = 8;
  public static final int INT = 13;
  public static final int WHILE = 21;
  public static final int SEMI = 2;
  public static final int NOT = 30;
  public static final int RETURN = 17;
  public static final int TRUE = 31;
  public static final int IF = 19;
  public static final int GT = 25;
  public static final int LPAREN = 7;
  public static final int LBRACE = 9;
  public static final int ID = 34;
  public static final int LE = 26;
  public static final int COMMA = 12;
  public static final int NUMBER = 33;
  public static final int FUNC = 18;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MAIN = 16;
  public static final int FALSE = 32;
  public static final int GE = 27;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 22;
  public static final int ASSIGN = 11;
  public static final int BOOL = 14;
  public static final int VOID = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "ASSIGN",
  "COMMA",
  "INT",
  "BOOL",
  "VOID",
  "MAIN",
  "RETURN",
  "FUNC",
  "IF",
  "ELSE",
  "WHILE",
  "EQ",
  "NE",
  "LT",
  "GT",
  "LE",
  "GE",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "NUMBER",
  "ID"
  };
}

